### ISSUE TITLE
Index Error in beamsearch

### ISSUE THREAD

**Issue by abhilashgahankari** [Adityak204/Translation-Model-Englist-to-Hindi#1]
while calling beam search, getting error
line 90, in beam_search
    trans_store[seq_prob[:, seq_id[:, ts + 1] == eos].squeeze()] = seq_id[seq_id[:, ts + 1] == eos, :].squeeze()
IndexError: The shape of the mask [5] at index 0 does not match the shape of the indexed tensor [1, 1, 5] at index 1.

**Comment by Adityak204** [comment]
Fixed the index error in the latest commit.
